

services:
  portfolio-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN=hamedaei.com
      - API_DOMAIN=api.hamedaei.com
      - ADMIN_DOMAIN=admin.hamedaei.com
      - CDN_DOMAIN=cdn.hamedaei.com
      - CORS_ORIGIN=https://hamedaei.com,https://www.hamedaei.com,https://api.hamedaei.com,https://admin.hamedaei.com,https://cdn.hamedaei.com
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      # اتصال به دیتابیس
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=muti
      - DB_PASSWORD=111111111
      - DB_NAME=muti
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - portfolio-network

  db:
    image: mysql:5.7
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portfolio-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - portfolio-api
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  db_data:
